exclude: "^venv/|/migrations/"
default_stages: [ pre-commit ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.14.1'
    hooks:
      - id: ruff
        args:
          - "--config=pyproject.toml"
          - "--unsafe-fixes"

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
      - id: black
        args:
          - "--config=pyproject.toml"

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.5.0
    hooks:
      - id: pycln
        args:
          - "--config=pyproject.toml"

  # - repo: https://github.com/PyCQA/docformatter
  #   rev: v1.7.5
  #   hooks:
  #     - id: docformatter
  #       args:
  #         - "--config=pyproject.toml"
  #         - "--in-place"


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args:
          - '--strict'
          - "--config=pyproject.toml"
          - "--no-namespace-packages"
          - "--enable-incomplete-feature=Unpack"
        additional_dependencies: [ pytest,"django-stubs[compatible-mypy]",telethon,types-requests  ]

ci:
    autofix_commit_msg: |
      🚨 Lint Fixes
    autofix_prs: true
    autoupdate_commit_msg: |
      ✨Update versions of tools in pre-commit configs to latest version
