[tool.ruff]
line-length = 120
target-version = "py311"
fix = true
show-fixes = true
[tool.ruff.lint]
select = [ "ALL"]
ignore = [
    "D401",
    "ANN401",
    "S603",
    "S607",
    "ARG002", #unused-method-argument
    "PTH122", #os-path-splitext
    "TRY301", #raise-within-try
    "PERF203", #try-except-in-loop
    "UP004", #useless-object-inheritance
    "PLR0911", #too many returns
    "S310", # Audit URL open for permitted schemes.
    "FBT003", # Audit URL open for permitted schemes.
    "BLE001", # Audit URL open for permitted schemes.
    "TRY300", # Audit URL open for permitted schemes.
    "D102", # Audit URL open for permitted schemes.
    "D100", # Audit URL open for permitted schemes.
    "D101", # Audit URL open for permitted schemes.
    "RUF012", # Audit URL open for permitted schemes.
    "PYI034", # Audit URL open for permitted schemes.
    "D104", # Audit URL open for permitted schemes.
    "ASYNC210", # Audit URL open for permitted schemes.
    "PLR2004", # Audit URL open for permitted schemes.
    "DTZ005", # Audit URL open for permitted schemes.
    "FBT001", # Audit URL open for permitted schemes.
    "PGH003", # Audit URL open for permitted schemes.
]
[tool.ruff.lint.pydocstyle]
convention = "numpy"
[tool.ruff.lint.per-file-ignores]
"test**.py" = ["S101","SLF001","PT019","S311","D102"]

[tool.docformatter]
recursive = true
wrap-summaries = 120
wrap-descriptions = 120

[tool.black]
line-length = 120

[pycodestyle]
max-line-length = 120
exclude = ["venv"]


[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "manage"

[tools.pytest]
pythonpath = ["esxport"]

[tool.pytest.ini_options]
addopts = "--cov=. --cov-report=xml --cov-report term-missing --ff -x --no-cov-on-fail --emoji --dist loadgroup --tx=4*popen"

[tool.coverage.run]
#branch = true #https://github.com/nedbat/coveragepy/issues/605
parallel = true

[tool.coverage.report]
skip_covered = true
skip_empty = true
show_missing=true
sort="-Stmts"
omit = ["test/**"]
exclude_lines = [
    'if TYPE_CHECKING:',
    'if __name__ == "__main__":'
    ]



[tool.pyright]
include = ["."]
typeCheckingMode = "strict"
exclude = ["**/test",]
reportMissingTypeStubs = false
