"""Strings."""
cleanup_success = "Gone.🧹"
something_bad_occurred = "Something bad happened.☠️"
no_input = "Please provide valid input."
ignore = "Ignoring request. zzzzzzz."
conversation_nf = "Conversation not found."
