# Generated by Django 4.2 on 2023-04-08 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, null=True)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "conversation",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, null=True)),
                ("telegram_id", models.IntegerField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "ACTIVE"),
                            ("suspended", "SUSPENDED"),
                            ("temporarily banned", "TEMP_BANNED"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("joining_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="UserImages",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image_caption", models.TextField(null=True)),
                ("image_url", models.TextField()),
                ("from_bot", models.BooleanField()),
                ("message_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sqlitedb.user"
                    ),
                ),
            ],
            options={
                "db_table": "user_images",
            },
        ),
        migrations.CreateModel(
            name="UserConversations",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("from_bot", models.BooleanField()),
                ("message_date", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sqlitedb.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sqlitedb.user"
                    ),
                ),
            ],
            options={
                "db_table": "user_conversations",
            },
        ),
        migrations.CreateModel(
            name="CurrentConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sqlitedb.conversation",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="sqlitedb.user"
                    ),
                ),
            ],
            options={
                "db_table": "current_conversation",
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sqlitedb.user"
            ),
        ),
    ]
